// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TFL.Infrastructure.Data;

#nullable disable

namespace TFL.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TflDbContext))]
    partial class TflDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TFL.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoNavigateToTransferredDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultMatchSchedule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RandomizePlayerOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecentMatchesToStore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPlayerStatusIcons")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoNavigateToTransferredDraft = true,
                            AutoSave = true,
                            DefaultMatchSchedule = "[{\"dayOfWeek\":2,\"time\":\"20:00\"},{\"dayOfWeek\":4,\"time\":\"20:00\"}]",
                            RandomizePlayerOrder = false,
                            RecentMatchesToStore = 8,
                            ShowPlayerStatusIcons = true
                        });
                });

            modelBuilder.Entity("TFL.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Roles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUsers_Email");

                    b.HasIndex("LinkedPlayerId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("TFL.Domain.Entities.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("TFL.Domain.Entities.DraftPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DraftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("DraftId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UX_DraftPlayers_DraftId_PlayerId");

                    b.ToTable("DraftPlayers");
                });

            modelBuilder.Entity("TFL.Domain.Entities.ExternalMailEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ExternalMailList");
                });

            modelBuilder.Entity("TFL.Domain.Entities.GameEvent", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Inactive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("Inactive")
                        .HasDatabaseName("IX_GameEvents_Inactive");

                    b.HasIndex("MatchDate")
                        .HasDatabaseName("IX_GameEvents_MatchDate");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("TFL.Domain.Entities.GameEventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameEventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReserve")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameEventName", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UX_GameEventRegistrations_EventName_PlayerId");

                    b.ToTable("GameEventRegistrations");
                });

            modelBuilder.Entity("TFL.Domain.Entities.Match", b =>
                {
                    b.Property<string>("DateKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AppliedResults")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SavedResult")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreTeam1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreTeam2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("DateKey");

                    b.HasIndex("LastModified")
                        .HasDatabaseName("IX_Matches_LastModified");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Matches_Status");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TFL.Domain.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchDateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RatingDiff")
                        .HasColumnType("REAL");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchDateKey", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UX_MatchPlayers_MatchDateKey_PlayerId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("TFL.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Affinity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<bool>("Reserve")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("IX_Players_IsArchived");

                    b.HasIndex("LastModified")
                        .HasDatabaseName("IX_Players_LastModified");

                    b.HasIndex("LinkedUserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TFL.Domain.Entities.PlayerRecentEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diff")
                        .HasColumnType("REAL");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_PlayerRecentEntries_PlayerId");

                    b.ToTable("PlayerRecentEntries");
                });

            modelBuilder.Entity("TFL.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("TFL.Domain.Entities.RatingSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RatingSnapshots");
                });

            modelBuilder.Entity("TFL.Domain.Entities.SyncConflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirestoreSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SqliteSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SyncConflicts_EntityType_EntityKey");

                    b.ToTable("SyncConflicts");
                });

            modelBuilder.Entity("TFL.Domain.Entities.SyncState", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityType");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("TFL.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("TFL.Domain.Entities.Player", "LinkedPlayer")
                        .WithMany()
                        .HasForeignKey("LinkedPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedPlayer");
                });

            modelBuilder.Entity("TFL.Domain.Entities.DraftPlayer", b =>
                {
                    b.HasOne("TFL.Domain.Entities.Draft", "Draft")
                        .WithMany("DraftPlayers")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFL.Domain.Entities.Player", "Player")
                        .WithMany("DraftPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TFL.Domain.Entities.GameEventRegistration", b =>
                {
                    b.HasOne("TFL.Domain.Entities.GameEvent", "GameEvent")
                        .WithMany("Registrations")
                        .HasForeignKey("GameEventName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFL.Domain.Entities.Player", "Player")
                        .WithMany("GameEventRegistrations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEvent");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TFL.Domain.Entities.MatchPlayer", b =>
                {
                    b.HasOne("TFL.Domain.Entities.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchDateKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFL.Domain.Entities.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TFL.Domain.Entities.Player", b =>
                {
                    b.HasOne("TFL.Domain.Entities.AppUser", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedUser");
                });

            modelBuilder.Entity("TFL.Domain.Entities.PlayerRecentEntry", b =>
                {
                    b.HasOne("TFL.Domain.Entities.Player", "Player")
                        .WithMany("RecentEntries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TFL.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("TFL.Domain.Entities.AppUser", "User")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TFL.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("PushSubscriptions");
                });

            modelBuilder.Entity("TFL.Domain.Entities.Draft", b =>
                {
                    b.Navigation("DraftPlayers");
                });

            modelBuilder.Entity("TFL.Domain.Entities.GameEvent", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("TFL.Domain.Entities.Match", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("TFL.Domain.Entities.Player", b =>
                {
                    b.Navigation("DraftPlayers");

                    b.Navigation("GameEventRegistrations");

                    b.Navigation("MatchPlayers");

                    b.Navigation("RecentEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
